name: Go

on:
  push:
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1
        id: go

      - name: Install gometalinter
        run: |
          go get github.com/alecthomas/gometalinter

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Run make
        run: |
          make style
          make vet
          make gometalinter
          make build
          make test
