name: Build and Test

on:
  push:
  pull_request:
    branches: [ awnmaster, master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Build and Test
        run: |
          make vet
          make test
          make build
